---
title: Shiny in Markdown
author: Scott Russell
date: May 2, 2018
output: html_document
runtime: shiny # this will spin up a webserver that serves a shiny app instead of rendering an html doc
---

# Select Input

```{r select-input}
selectInput(
    inputId='StateSelection',
    label='Please choose a state',
    choices=list('NY', 'NJ', 'MA', 'RI', 'TX'),
    selected='MA'
)
```

If you want to run in RStudio, be sure to load `library('shiny')`, then Ctrl+Shift+Enter in the chunk to execute it. This returns the generated HTML:

```{html}
<div class="form-group shiny-input-container">
  <label class="control-label" for="StateSelection">Please choose a state</label>
  <div>
    <select id="StateSelection"><option value="NY">NY</option>
<option value="NJ">NJ</option>
<option value="MA" selected>MA</option>
<option value="RI">RI</option>
<option value="TX">TX</option></select>
    <script type="application/json" data-for="StateSelection" data-nonempty="">{}</script>
  </div>
</div>
```

## Select Input and Print Selection

```{r print-state}
renderText(input$StateSelection)
```

# Other Inputs

```{r other-inputs}
sliderInput(
    inputId = 'SliderSample',
    label = 'This is a slider',
    min=0, max=10, value=5 # set min max and starting/default values
)

checkboxInput(
    inputId = 'CheckSample',
    label = 'Check this'
)

radioButtons(
    inputId = 'RadioSample',
    label = 'Choose one',
    choices = list('AB', 'A', 'B', 'O')
)

dateInput(
    inputId = 'DateChoice',
    label = 'Select a date'
)

dateRangeInput(
    inputId = 'DateRangeChoice',
    label = 'Choose your dates'
)
```

# Text Input

```{r text-inputs}
textInput(
    inputId = 'TextSample',
    label = 'Write something',
    placeholder = 'Write on the ghost'
)

textAreaInput(
    inputId = 'TextAreaSample',
    label = 'Write a long passage'
)

passwordInput(
    inputId = 'PasswordSample',
    label = 'Enter the secret'
)

renderText(input$PasswordSample)
```

# Showing Data

```{r render-tables}
renderTable(mtcars) # this is the old-fashioned way of doing this

renderDataTable(mtcars) # this is an old version of JS:datatable library built into Shiny a long time ago

# There is a better, newer version of datatable, DT, available in R
# Needed to install the package install.packages('DT')
DT::renderDataTable(mtcars)
```

# Plots

```{r render-plot}
renderPlot(hist(mtcars$mpg)) # boring static plot
```

```{r render-choices}
selectInput(
    inputId = 'PlotColumn',
    label = 'Choose a column',
    choices = names(mtcars)
)

sliderInput(
    inputId = 'Bins',
    label = 'Choose number of bins',
    min = 5, max = 50, value = 30
)
```

```{r gg-hist}
library(ggplot2) # better in shiny apps to load at top of doc

renderPlot(
    ggplot(mtcars, aes_string(x=input$PlotColumn)) + geom_histogram(bins=input$Bins)
)
```

```{r render-plotly}
# Install the plotly package install.package('plotly')
plotly::renderPlotly(
    plotly::ggplotly( # this call isn't necessary for shiny, but may be necessary for calling just within RMarkdown
        ggplot(mtcars, aes_string(x=input$PlotColumn)) + geom_histogram(bins=input$Bins)
    )
)
```

